{% set name = "pyTCR" %}
{% set version = "1.2.3" %}
{% set python_min = "3.11" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pytcr-{{ version }}.tar.gz
  sha256: 7bd667acdca79a4893529f4ced20272ea8ca7635d17513077db8f0193b990eed

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - cartopy
    - colorcet
    - geopandas
    - jupyter
    - matplotlib-base
    - netcdf4
    - pyproj
    - requests
    - scipy
    - shapely
    - xarray
    - beautifulsoup4

test:
  imports:
    - tcr
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/levuvietphong/pyTCR
  summary: A tropical cyclone rainfall model for python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - levuvietphong
